### ISSUE TITLE
Wildfly-Swarm Health-check booster Jenkins build is failing.

### ISSUE THREAD

**Issue by ravsa** [fabric8-launcher/launcher-booster-catalog#189] opened 2018-04-10 11:16 UTC
wildfly-swarm health-check RHOAR booster is failing at jenkins build here is log
```log
Picked up _JAVA_OPTIONS: -Duser.home=/root/ -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Xms10m -Xmx192m
Wed Apr 04 14:15:53 UTC 2018 INFO [org.wildfly.swarm.bootstrap] (main) Dependencies not bundled; resolving from M2REPO.
[0m2018-04-04 14:16:19,191 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:               Arquillian - STABLE          org.wildfly.swarm:arquillian:2017.10.2
[0m[0m2018-04-04 14:16:19,206 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                  Logging - STABLE          org.wildfly.swarm:logging:7.0.1.redhat-20
[0m[0m2018-04-04 14:16:19,207 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:        CDI Configuration - STABLE          org.wildfly.swarm:cdi-config:7.0.1.redhat-20
[0m[0m2018-04-04 14:16:19,207 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                   JAX-RS - STABLE          org.wildfly.swarm:jaxrs:7.0.1.redhat-20
[0m[0m2018-04-04 14:16:19,207 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:               Management - STABLE          org.wildfly.swarm:management:7.0.1.redhat-20
[0m[0m2018-04-04 14:16:19,207 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:          Bean Validation - STABLE          org.wildfly.swarm:bean-validation:7.0.1.redhat-20
[0m[0m2018-04-04 14:16:19,207 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:             Transactions - STABLE          org.wildfly.swarm:transactions:7.0.1.redhat-20
[0m[0m2018-04-04 14:16:19,208 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                  Monitor - STABLE          org.wildfly.swarm:monitor:7.0.1.redhat-20
[0m[0m2018-04-04 14:16:19,208 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                      CDI - STABLE          org.wildfly.swarm:cdi:7.0.1.redhat-20
[0m[0m2018-04-04 14:16:19,208 INFO  [org.wildfly.swarm] (main) WFSWARM0013: Installed fraction:                 Undertow - STABLE          org.wildfly.swarm:undertow:7.0.1.redhat-20
[0m[0m2018-04-04 14:16:26,100 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.7.SP1-redhat-1
[0m[0m2018-04-04 14:16:26,315 INFO  [org.jboss.as] (MSC service thread 1-7) WFLYSRV0049: WildFly Core 2.1.18.Final-redhat-1 "Kenny" starting
[0m[0m2018-04-04 14:16:26,792 INFO  [org.wildfly.swarm] (MSC service thread 1-7) WFSWARM0019: Install MSC service for command line args: []
[0m[0m2018-04-04 14:16:27,926 INFO  [org.wildfly.swarm.arquillian.daemon.server.Server] (MSC service thread 1-6) Arquillian Daemon server started on localhost:12345
[0m[33m2018-04-04 14:16:28,197 WARN  [org.wildfly.swarm.monitor.health] (MSC service thread 1-8) You are running the monitoring endpoints without any security realm configuration!
[0m[33m2018-04-04 14:16:36,225 WARN  [org.jboss.as.txn] (ServerService Thread Pool -- 14) WFLYTX0013: Node identifier property is set to the default value. Please make sure it is unique.
[0m[0m2018-04-04 14:16:36,296 INFO  [org.jboss.as.naming] (ServerService Thread Pool -- 15) WFLYNAM0001: Activating Naming Subsystem
[0m[0m2018-04-04 14:16:36,299 INFO  [org.jboss.as.security] (ServerService Thread Pool -- 20) WFLYSEC0002: Activating Security Subsystem
[0m[0m2018-04-04 14:16:36,310 INFO  [org.jboss.as.security] (MSC service thread 1-2) WFLYSEC0001: Current PicketBox version=4.9.8.Final-redhat-1
[0m[0m2018-04-04 14:16:36,415 INFO  [org.wildfly.extension.io] (ServerService Thread Pool -- 22) WFLYIO001: Worker 'default' has auto-configured to 16 core threads with 128 task threads based on your 8 available processors
[0m[0m2018-04-04 14:16:36,503 INFO  [org.jboss.as.naming] (MSC service thread 1-5) WFLYNAM0003: Starting Naming Service
[0m[0m2018-04-04 14:16:37,602 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0003: Undertow 1.3.31.Final-redhat-1 starting
[0m[0m2018-04-04 14:16:37,602 INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 18) WFLYUT0003: Undertow 1.3.31.Final-redhat-1 starting
[0m[0m2018-04-04 14:16:37,807 INFO  [org.xnio] (MSC service thread 1-2) XNIO version 3.4.6.Final-redhat-1
[0m[0m2018-04-04 14:16:38,100 INFO  [org.xnio.nio] (MSC service thread 1-2) XNIO NIO Implementation Version 3.4.6.Final-redhat-1
[0m[0m2018-04-04 14:16:38,203 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0012: Started server default-server.
[0m[0m2018-04-04 14:16:38,204 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-4) WFLYUT0018: Host default-host starting
[0m[0m2018-04-04 14:16:38,396 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-5) WFLYUT0006: Undertow HTTP listener default listening on 0.0.0.0:8080
[0m[0m2018-04-04 14:16:38,415 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0039: Creating http management service using socket-binding (management-http)
[0m[33m2018-04-04 14:16:38,416 WARN  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0035: No security realm defined for http management service; all access will be unrestricted.
[0m[0m2018-04-04 14:16:38,509 INFO  [org.jboss.remoting] (MSC service thread 1-1) JBoss Remoting version 4.0.24.Final-redhat-1
[0m[31m2018-04-04 14:16:38,703 ERROR [stderr] (Controller Boot Thread) java.io.IOException: Mount point not found
[0m[31m2018-04-04 14:16:38,704 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.LinuxFileStore.findMountEntry(LinuxFileStore.java:91)
[0m[31m2018-04-04 14:16:38,704 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.UnixFileStore.<init>(UnixFileStore.java:65)
[0m[31m2018-04-04 14:16:38,704 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.LinuxFileStore.<init>(LinuxFileStore.java:44)
[0m[31m2018-04-04 14:16:38,704 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:51)
[0m[31m2018-04-04 14:16:38,705 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.LinuxFileSystemProvider.getFileStore(LinuxFileSystemProvider.java:39)
[0m[31m2018-04-04 14:16:38,705 ERROR [stderr] (Controller Boot Thread) 	at sun.nio.fs.UnixFileSystemProvider.getFileStore(UnixFileSystemProvider.java:368)
[0m[31m2018-04-04 14:16:38,705 ERROR [stderr] (Controller Boot Thread) 	at java.nio.file.Files.getFileStore(Files.java:1461)
[0m[31m2018-04-04 14:16:38,705 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.getPosixAttributes(FilePersistenceUtils.java:129)
[0m[31m2018-04-04 14:16:38,705 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.createTempFileWithAttributes(FilePersistenceUtils.java:117)
[0m[31m2018-04-04 14:16:38,705 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.FilePersistenceUtils.writeToTempFile(FilePersistenceUtils.java:104)
[0m[31m2018-04-04 14:16:38,706 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.FilePersistenceResource.doCommit(FilePersistenceResource.java:51)
[0m[31m2018-04-04 14:16:38,706 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.persistence.AbstractFilePersistenceResource.commit(AbstractFilePersistenceResource.java:58)
[0m[31m2018-04-04 14:16:38,706 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.ModelControllerImpl$4.commit(ModelControllerImpl.java:791)
[0m[31m2018-04-04 14:16:38,706 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractOperationContext.executeDoneStage(AbstractOperationContext.java:743)
[0m[31m2018-04-04 14:16:38,706 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:680)
[0m[31m2018-04-04 14:16:38,707 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:370)
[0m[31m2018-04-04 14:16:38,707 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1349)
[0m[31m2018-04-04 14:16:38,707 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:495)
[0m[31m2018-04-04 14:16:38,707 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:389)
[0m[31m2018-04-04 14:16:38,707 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:351)
[0m[31m2018-04-04 14:16:38,707 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.server.ServerService.boot(ServerService.java:402)
[0m[31m2018-04-04 14:16:38,708 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.server.ServerService.boot(ServerService.java:371)
[0m[31m2018-04-04 14:16:38,708 ERROR [stderr] (Controller Boot Thread) 	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:301)
[0m[31m2018-04-04 14:16:38,708 ERROR [stderr] (Controller Boot Thread) 	at java.lang.Thread.run(Thread.java:748)
[0m[0m2018-04-04 14:16:38,911 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://127.0.0.1:9990/management
[0m[0m2018-04-04 14:16:38,912 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
[0m[0m2018-04-04 14:16:38,912 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Core 2.1.18.Final-redhat-1 "Kenny" started in 13005ms - Started 111 of 117 services (25 services are lazy, passive or on-demand)
[0m[0m2018-04-04 14:16:41,345 INFO  [org.wildfly.swarm.monitor.health] (main) Adding /health endpoint delegate: /api/service/health
[0m[0m2018-04-04 14:16:41,882 INFO  [org.wildfly.swarm.runtime.deployer] (main) deploying GreetingServiceTest.war
[0m[0m2018-04-04 14:16:41,919 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-7) WFLYSRV0027: Starting deployment of "GreetingServiceTest.war" (runtime-name: "GreetingServiceTest.war")
[0m
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 450.531 s <<< FAILURE! - in io.openshift.boosters.GreetingServiceTest
[ERROR] io.openshift.boosters.GreetingServiceTest  Time elapsed: 450.53 s  <<< ERROR!
```
..... [More Log](https://gist.github.com/ravsa/b022b71bee5fda1f5dc5436b61c09609)

**Comment by kenfinnigan** [comment] 2018-04-10 12:11
@ravsa, that's caused by an incorrectly configured OpenShift environment.

We've seen it previously in OpenShift Starter/Pro in some clusters that weren't configured properly, but don't believe it happens in those anymore

**Comment by kenfinnigan** [comment] 2018-04-12 10:49
@slemeur As discussed in the linked issue from @Ladicek, there are fixes for this problem in WF Core but 7.0.1 of WF Swarm doesn't contain that fix.

It won't be fixed in WF Swarm product until 7.1.0 is released, which is likely some time in May

**Comment by GeorgeActon** [comment] 2018-04-13 11:12
Who does this affect, just OSIO or everyone outside of OSIO as well.

**Comment by kenfinnigan** [comment] 2018-04-13 11:56
I believe right now it's OSIO, and maybe some OSO clusters

**Comment by GeorgeActon** [comment] 2018-04-13 13:36
@kenfinnigan so is this being pulled from the catalogue until the fix is in? 

How will a user be informed that it may have issues and in what cases?

**Comment by kenfinnigan** [comment] 2018-04-13 13:38
Pulled from what catalog?

It's not being removed from the Booster Catalog, if that's what you meant

**Comment by gastaldi** [comment] 2018-04-23 13:31
@ravsa this is not the correct repository to open such issues. Closing as it is tracked in https://issues.jboss.org/browse/SWARM-1701

**Closed by gastaldi** 2018-04-23 13:31 UTC
